### ISSUE TITLE
Breaking GitHub templates

### ISSUE THREAD

**Issue by Borda** [hukkin/mdformat-gfm#12]
### Describe the problem

I have deployed which changed my Github issue head from
```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug / fix, help wanted
assignees: ''

---
```
to
```
______________________________________________________________________

name: Bug report
about: Create a report to help us improve
title: ''
labels: bug / fix, help wanted
assignees: ''

______________________________________________________________________
```
which is no longer recognised by Github as Issue template

### Steps to reproduce

run pre-commit according to docs:
```
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.7
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
```

### Additional context

https://github.com/executablebooks/mdformat/issues/246
